repos:
  - repo: local
    hooks:
      - id: ktlint-format
        name: ktlint format
        language: system
        entry: ./gradlew ktlintFormat
        pass_filenames: false
        files: \.(kt|kts)$
        stages: [pre-commit]
      - id: ktlint-check
        name: ktlint check
        language: system
        entry: ./gradlew ktlintCheck
        pass_filenames: false
        files: \.(kt|kts)$
        stages: [pre-commit]
